# Generated by Django 4.2 on 2025-06-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('fecha_siembra', models.DateField(auto_now=True, verbose_name='Fecha de siembra')),
                ('fecha_cosecha', models.DateField(verbose_name='Fecha de cosecha')),
                ('temporada', models.IntegerField(verbose_name='Temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Plastico_usado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (kg)')),
                ('fecha_uso', models.DateField(auto_now=True, verbose_name='Fecha de uso')),
                ('origen', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Reciclado', 'Reciclado')], default='Nuevo', max_length=10, verbose_name='Origen')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo', verbose_name='Cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Plastico_desechado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (kg)')),
                ('fecha_desecho', models.DateField(auto_now=True, verbose_name='Fecha de desecho')),
                ('reciclado', models.BooleanField(default=False, verbose_name='¿Plástico reciclado?')),
                ('pla_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plastico_usado', verbose_name='Plástico')),
            ],
        ),
    ]
