# Generated by Django 4.2 on 2025-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='XXXXXXXX-X', max_length=12, verbose_name='RUT'),
        ),
    ]
