# Generated by Django 4.2 on 2025-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleado_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_cosecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cosecha'),
        ),
    ]
